export type ProductSpec = {
  label: string
  value: string
}

export type ProductFeature = string

export type Product = {
  model: string
  slug: string
  name: string
  category: string
  categoryName: string
  size: string
  type: string
  badge?: string | null
  tagline: string
  description: string
  features: ProductFeature[]
  specs: ProductSpec[]
  applications: string[]
  inputs?: string[]
  outputs?: string[]
  communication?: string[]
  supply?: string
  approvals?: string[]
  image?: string
  images?: string[]
}

export const ALL_PRODUCTS: Product[] = [
  // ─── Temperature Controllers ────────────────────────────────────────────────
  {
    model: 'AI-5442',
    slug: 'ai-5442',
    name: 'Temperature Controller AI-5442',
    category: 'temperature-controllers',
    categoryName: 'Temperature Controllers',
    size: '48×48 MM',
    type: 'Single Row, Single Output',
    badge: null,
    tagline: 'Compact 48×48 PID/ON-OFF controller with TC & RTD input',
    description:
      'The AI-5442 is a compact 48×48 MM panel-mount temperature controller offering PID and ON-OFF control modes. It accepts J, K, R, S thermocouple and Pt-100 RTD sensors, making it ideal for space-constrained panel installations.',
    features: [
      'PID and ON-OFF control modes',
      'Selectable J, K, R, S thermocouple input',
      'Pt-100 RTD 3-wire input',
      'Single relay output',
      'Bright red LED display',
      '125 ms sampling rate',
      'Setpoint lock / parameter lock',
      'Wide supply: 90–270 VAC',
    ],
    specs: [
      { label: 'Panel Size', value: '48×48 MM' },
      { label: 'Display', value: '4-digit LED, Red' },
      { label: 'Sensor Input', value: 'J, K, R, S TC + Pt-100 RTD' },
      { label: 'Control Mode', value: 'PID / ON-OFF' },
      { label: 'Output', value: '1 Relay (SPDT)' },
      { label: 'Sampling Rate', value: '125 ms' },
      { label: 'Supply', value: '90–270 VAC, 50/60 Hz' },
      { label: 'Power Consumption', value: '≤ 5 VA' },
      { label: 'Operating Temp', value: '0–50 °C' },
      { label: 'Storage Temp', value: '-20–65 °C' },
      { label: 'Humidity', value: '≤ 85% RH non-condensing' },
      { label: 'Protection', value: 'IP54 (front panel)' },
    ],
    inputs: ['J Thermocouple', 'K Thermocouple', 'R Thermocouple', 'S Thermocouple', 'Pt-100 RTD (3-wire)'],
    outputs: ['1 × SPDT Relay (3A / 250VAC)'],
    applications: ['Ovens & dryers', 'Incubators', 'Sealing machines', 'Small furnaces', 'Plastics processing'],
    supply: '90–270 VAC',
    image: 'https://itherm.co.in/wp-content/uploads/2025/01/1-Digital-Temp-Contro.jpg',
    images: [
      'https://itherm.co.in/wp-content/uploads/2025/01/1-Digital-Temp-Contro.jpg',
      'https://itherm.co.in/wp-content/uploads/2025/01/2-PID-Temp-Contro.jpg',
      'https://itherm.co.in/wp-content/uploads/2024/12/Cx-928-1-300x300.jpg',
    ],
  },
  {
    model: 'AI-5742',
    slug: 'ai-5742',
    name: 'Temperature Controller AI-5742',
    category: 'temperature-controllers',
    categoryName: 'Temperature Controllers',
    size: '72×72 MM',
    type: 'Single Row, Two Output',
    badge: null,
    tagline: 'Versatile 72×72 PID controller with relay + SSR drive output',
    description:
      'The AI-5742 is a 72×72 MM temperature controller with dual outputs — a relay and an SSR drive — enabling simultaneous heating and cooling or alarm control. Widely used in plastics, food processing, and packaging applications.',
    features: [
      'PID / ON-OFF control',
      'Dual output: relay + SSR drive',
      'Auto-tune for PID parameters',
      'Alarm output relay',
      'Selectable TC & RTD input',
      'Parameter protection lock',
      'Sub-range input calibration',
      '125 ms sampling',
    ],
    specs: [
      { label: 'Panel Size', value: '72×72 MM' },
      { label: 'Display', value: '4-digit LED (SV & PV)' },
      { label: 'Sensor Input', value: 'J, K, R, S TC + Pt-100 RTD' },
      { label: 'Control Mode', value: 'PID / ON-OFF' },
      { label: 'Output 1', value: 'Relay (SPDT, 3A / 250VAC)' },
      { label: 'Output 2', value: 'SSR Drive (12VDC, 30mA)' },
      { label: 'Sampling Rate', value: '125 ms' },
      { label: 'Supply', value: '90–270 VAC, 50/60 Hz' },
      { label: 'Power Consumption', value: '≤ 5 VA' },
      { label: 'Protection', value: 'IP54 (front panel)' },
    ],
    inputs: ['J Thermocouple', 'K Thermocouple', 'R Thermocouple', 'S Thermocouple', 'Pt-100 RTD (3-wire)'],
    outputs: ['Relay (SPDT, 3A / 250VAC)', 'SSR Drive (12VDC, 30mA)'],
    applications: ['Plastic moulding machines', 'Packaging equipment', 'Industrial ovens', 'Dye bath control', 'Heat sealers'],
    supply: '90–270 VAC',
    image: 'https://itherm.co.in/wp-content/uploads/2025/01/1-Digital-Temp-Contro.jpg',
  },
  {
    model: 'AI-5942',
    slug: 'ai-5942',
    name: 'Temperature Controller AI-5942',
    category: 'temperature-controllers',
    categoryName: 'Temperature Controllers',
    size: '96×48 MM',
    type: 'Single Row',
    badge: null,
    tagline: 'Wide-format 96×48 controller for DIN rail panel layouts',
    description:
      'The AI-5942 in 96×48 MM form factor fits horizontal panel layouts. It offers PID control with relay output and is suitable for retort temperature control, food processing, and chemical batch applications.',
    features: [
      'Horizontal 96×48 MM format',
      'PID and ON-OFF control',
      'J, K, R, S TC + Pt-100 RTD input',
      'Relay output',
      '4-digit LED display',
      'Auto-tune',
      'Setpoint lock',
    ],
    specs: [
      { label: 'Panel Size', value: '96×48 MM' },
      { label: 'Display', value: '4-digit LED' },
      { label: 'Sensor Input', value: 'J, K, R, S TC + Pt-100 RTD' },
      { label: 'Control Mode', value: 'PID / ON-OFF' },
      { label: 'Output', value: 'Relay (SPDT)' },
      { label: 'Supply', value: '90–270 VAC, 50/60 Hz' },
      { label: 'Protection', value: 'IP54 (front panel)' },
    ],
    inputs: ['J Thermocouple', 'K Thermocouple', 'R Thermocouple', 'S Thermocouple', 'Pt-100 RTD (3-wire)'],
    outputs: ['1 × SPDT Relay'],
    applications: ['Retort temperature control', 'Chemical batch', 'Food processing', 'Autoclave auxiliary'],
    supply: '90–270 VAC',
    image: 'https://itherm.co.in/wp-content/uploads/2025/01/1-Digital-Temp-Contro.jpg',
  },
  {
    model: 'AI-7481',
    slug: 'ai-7481',
    name: 'Temperature Controller AI-7481',
    category: 'temperature-controllers',
    categoryName: 'Temperature Controllers',
    size: '48×96 MM',
    type: 'Dual Row, Single Output',
    badge: null,
    tagline: 'Vertical 48×96 dual-display controller with RS485',
    description:
      'The AI-7481 offers a dual-row display in a 48×96 MM vertical panel format, showing both process value and setpoint simultaneously. It includes RS485 Modbus RTU for SCADA integration.',
    features: [
      'Dual row 4+4 digit display (PV + SV)',
      '48×96 MM vertical format',
      'PID / ON-OFF control',
      'RS485 Modbus RTU communication',
      'Auto-tune',
      'J, K, R, S TC + Pt-100 RTD',
      'Alarm relay',
    ],
    specs: [
      { label: 'Panel Size', value: '48×96 MM' },
      { label: 'Display', value: 'Dual row 4-digit LED' },
      { label: 'Sensor Input', value: 'J, K, R, S TC + Pt-100 RTD' },
      { label: 'Control Mode', value: 'PID / ON-OFF' },
      { label: 'Output', value: 'Relay (SPDT)' },
      { label: 'Communication', value: 'RS485 Modbus RTU' },
      { label: 'Supply', value: '90–270 VAC, 50/60 Hz' },
      { label: 'Protection', value: 'IP54 (front panel)' },
    ],
    inputs: ['J, K, R, S Thermocouple', 'Pt-100 RTD (3-wire)'],
    outputs: ['Relay (SPDT)'],
    communication: ['RS485 Modbus RTU'],
    applications: ['SCADA-linked control panels', 'Process monitoring stations', 'Industrial automation'],
    supply: '90–270 VAC',
    image: 'https://itherm.co.in/wp-content/uploads/2025/01/2-PID-Temp-Contro.jpg',
  },
  {
    model: 'AI-7482',
    slug: 'ai-7482',
    name: 'Temperature Controller AI-7482',
    category: 'temperature-controllers',
    categoryName: 'Temperature Controllers',
    size: '48×96 MM',
    type: 'Dual Row, Two Output',
    badge: null,
    tagline: 'Two-output 48×96 controller for heating & cooling',
    description:
      'The AI-7482 adds a second output to the 48×96 vertical form factor, enabling simultaneous heating and cooling control. Suitable for environmental chambers and humidity control panels.',
    features: [
      'Dual output for heat + cool control',
      'Dual row PV + SV display',
      'RS485 Modbus RTU',
      'Auto-tune PID',
      'Alarm relay',
      'TC + RTD input',
    ],
    specs: [
      { label: 'Panel Size', value: '48×96 MM' },
      { label: 'Display', value: 'Dual row 4-digit LED' },
      { label: 'Sensor Input', value: 'J, K, R, S TC + Pt-100 RTD' },
      { label: 'Output 1', value: 'Relay (SPDT)' },
      { label: 'Output 2', value: 'SSR Drive / Relay' },
      { label: 'Communication', value: 'RS485 Modbus RTU' },
      { label: 'Supply', value: '90–270 VAC, 50/60 Hz' },
    ],
    inputs: ['J, K, R, S Thermocouple', 'Pt-100 RTD (3-wire)'],
    outputs: ['Relay (SPDT)', 'SSR Drive or Second Relay'],
    communication: ['RS485 Modbus RTU'],
    applications: ['Environmental chambers', 'Cooling and heating systems', 'Stability chambers'],
    supply: '90–270 VAC',
    image: 'https://itherm.co.in/wp-content/uploads/2025/01/2-PID-Temp-Contro.jpg',
  },
  {
    model: 'AI-7782',
    slug: 'ai-7782',
    name: 'Temperature Controller AI-7782',
    category: 'temperature-controllers',
    categoryName: 'Temperature Controllers',
    size: '72×72 MM',
    type: '4 Digit Dual Row',
    badge: null,
    tagline: 'High-performance 72×72 dual-display PID controller',
    description:
      'The AI-7782 combines dual-row display, two control outputs, and RS485 Modbus communication in a 72×72 MM package. Ideal for precise process control requiring SCADA integration.',
    features: [
      'Dual row display: PV + SV',
      'Two control outputs',
      'RS485 Modbus RTU',
      'Auto-tune PID algorithm',
      'Ramp & soak program (optional)',
      'Alarm + fault indication',
    ],
    specs: [
      { label: 'Panel Size', value: '72×72 MM' },
      { label: 'Display', value: '2 × 4-digit LED' },
      { label: 'Sensor Input', value: 'J, K, R, S TC + Pt-100 RTD' },
      { label: 'Control Mode', value: 'PID / ON-OFF' },
      { label: 'Output 1', value: 'Relay (SPDT)' },
      { label: 'Output 2', value: 'SSR Drive (12VDC)' },
      { label: 'Communication', value: 'RS485 Modbus RTU' },
      { label: 'Supply', value: '90–270 VAC' },
      { label: 'Protection', value: 'IP54 (front panel)' },
    ],
    inputs: ['J, K, R, S Thermocouple', 'Pt-100 RTD (3-wire)'],
    outputs: ['Relay (SPDT)', 'SSR Drive (12VDC, 30mA)'],
    communication: ['RS485 Modbus RTU'],
    applications: ['Furnaces', 'Heat treatment', 'Textile dyeing', 'Chemical reactors'],
    supply: '90–270 VAC',
    image: 'https://itherm.co.in/wp-content/uploads/2025/01/2-PID-Temp-Contro.jpg',
  },
  {
    model: 'AI-7982',
    slug: 'ai-7982',
    name: 'Temperature Controller AI-7982',
    category: 'temperature-controllers',
    categoryName: 'Temperature Controllers',
    size: '96×96 MM',
    type: '4 Digit Dual Row',
    badge: 'Popular',
    tagline: 'Flagship 96×96 PID controller — the industry standard choice',
    description:
      'The AI-7982 is I-Therm\'s most popular temperature controller in the 96×96 MM format. Featuring dual-row display, advanced PID auto-tune, two control outputs, and RS485 Modbus RTU communication. A go-to controller for pharmaceutical, food processing, textile, and industrial applications.',
    features: [
      'Dual row display: PV (upper) + SV (lower)',
      'Advanced auto-tune PID',
      'ON-OFF control mode',
      'Two independent control outputs',
      'RS485 Modbus RTU (optional)',
      'Alarm relay with deviation / abs limits',
      'Manual / Auto output mode',
      'Input calibration offset',
      'Power-fail setpoint retention',
      'Parameter / setpoint lock',
    ],
    specs: [
      { label: 'Panel Size', value: '96×96 MM' },
      { label: 'Cutout', value: '92×92 MM' },
      { label: 'Display', value: '2 × 4-digit LED (PV red, SV green)' },
      { label: 'Sensor Input', value: 'J, K, R, S TC + Pt-100 RTD' },
      { label: 'Input Resolution', value: '0.1°C / 1°C selectable' },
      { label: 'Control Mode', value: 'PID / ON-OFF' },
      { label: 'Output 1', value: 'Relay (SPDT, 3A / 250VAC)' },
      { label: 'Output 2', value: 'SSR Drive (12VDC, 30mA)' },
      { label: 'Alarm', value: '1 Relay (configurable deviation/absolute)' },
      { label: 'Communication', value: 'RS485 Modbus RTU (optional)' },
      { label: 'Sampling Rate', value: '125 ms' },
      { label: 'Supply', value: '90–270 VAC, 50/60 Hz' },
      { label: 'Power Consumption', value: '≤ 8 VA' },
      { label: 'Operating Temp', value: '0–50 °C' },
      { label: 'Humidity', value: '≤ 85% RH non-condensing' },
      { label: 'Protection', value: 'IP54 (front), IP20 (rear)' },
      { label: 'Weight', value: '≈ 300 g' },
    ],
    inputs: ['J Thermocouple (0–900°C)', 'K Thermocouple (0–1300°C)', 'R Thermocouple (0–1700°C)', 'S Thermocouple (0–1700°C)', 'Pt-100 RTD 3-wire (-50–600°C)'],
    outputs: ['Relay (SPDT, 3A / 250VAC)', 'SSR Drive (12VDC, 30mA)', 'Alarm Relay'],
    communication: ['RS485 Modbus RTU (optional)'],
    applications: [
      'Pharmaceutical — Autoclave & sterilization',
      'Food Processing — Retort, oven, pasteurization',
      'Textile Dyeing — Dye bath temperature',
      'Plastics — Injection moulding barrel',
      'Chemical — Reactor temperature',
      'Furnaces — Heat treatment',
    ],
    supply: '90–270 VAC',
    approvals: ['CE Marked'],
    image: 'https://itherm.co.in/wp-content/uploads/2025/01/2-PID-Temp-Contro.jpg',
  },
  {
    model: 'AI-7983',
    slug: 'ai-7983',
    name: 'Temperature Controller AI-7983',
    category: 'temperature-controllers',
    categoryName: 'Temperature Controllers',
    size: '96×96 MM',
    type: '4 Digit Dual Row, Three Output',
    badge: null,
    tagline: 'Three-output 96×96 controller for complex process control',
    description:
      'The AI-7983 adds a third output to the flagship 96×96 form factor for applications requiring heating, cooling, and alarm simultaneously — ideal for environmental chambers and stability rooms.',
    features: [
      'Three independent outputs',
      'Dual row PV + SV display',
      'Advanced PID + ON-OFF',
      'RS485 Modbus RTU',
      'Heating + cooling + alarm',
      'Auto-tune PID',
    ],
    specs: [
      { label: 'Panel Size', value: '96×96 MM' },
      { label: 'Sensor Input', value: 'J, K, R, S TC + Pt-100 RTD' },
      { label: 'Output 1', value: 'Relay (heating)' },
      { label: 'Output 2', value: 'Relay (cooling)' },
      { label: 'Output 3', value: 'Alarm Relay' },
      { label: 'Communication', value: 'RS485 Modbus RTU' },
      { label: 'Supply', value: '90–270 VAC' },
    ],
    inputs: ['J, K, R, S Thermocouple', 'Pt-100 RTD'],
    outputs: ['Relay (heat)', 'Relay (cool)', 'Alarm Relay'],
    communication: ['RS485 Modbus RTU'],
    applications: ['Environmental chambers', 'Stability rooms', 'Climate test chambers'],
    supply: '90–270 VAC',
    image: 'https://itherm.co.in/wp-content/uploads/2025/01/2-PID-Temp-Contro.jpg',
  },

  // ─── Timers & Counters ──────────────────────────────────────────────────────
  {
    model: 'KCN-444',
    slug: 'kcn-444',
    name: 'Digital Counter KCN-444',
    category: 'timers-counters',
    categoryName: 'Timers & Counters',
    size: '48×48 MM',
    type: 'Single Set Point Counter',
    badge: null,
    tagline: 'Compact 48×48 I-Count preset counter',
    description:
      'The KCN-444 is a compact 48×48 MM 4-digit preset counter from the I-Count range. Features single set point and relay output for batch counting, machine counting, and production monitoring.',
    features: [
      '4-digit LED display',
      'Single preset set point',
      'Relay output on set point',
      'Count up / count down',
      'External reset input',
      'Batch counting mode',
      'Wide supply 90–270 VAC',
    ],
    specs: [
      { label: 'Panel Size', value: '48×48 MM' },
      { label: 'Display', value: '4-digit LED' },
      { label: 'Count Digits', value: '4 digits (0–9999)' },
      { label: 'Set Points', value: '1' },
      { label: 'Output', value: '1 Relay (SPDT)' },
      { label: 'Input', value: 'NPN / PNP / Voltage pulse' },
      { label: 'Supply', value: '90–270 VAC' },
    ],
    inputs: ['NPN sensor input', 'PNP sensor input', 'Voltage pulse (5–24VDC)'],
    outputs: ['1 × SPDT Relay'],
    applications: ['Batch counting', 'Production monitoring', 'Machine stroke counting', 'Packaging lines'],
    supply: '90–270 VAC',
    image: 'https://itherm.co.in/wp-content/uploads/2024/12/Cx-928-1-300x300.jpg',
  },
  {
    model: 'KCN-888',
    slug: 'kcn-888',
    name: 'Digital Counter KCN-888',
    category: 'timers-counters',
    categoryName: 'Timers & Counters',
    size: '96×96 MM',
    type: 'Dual Set Point Counter',
    badge: null,
    tagline: '6-digit dual set point counter with batch & totalizer modes',
    description:
      'The KCN-888 is a 96×96 MM 6-digit preset counter with dual set points and two relay outputs. Supports count up, count down, batch, and totalizer modes. Widely used in textile, packaging, and manufacturing lines.',
    features: [
      '6-digit LED display',
      'Dual set point (SP1 + SP2)',
      'Two relay outputs',
      'Count up & count down',
      'Batch counting with auto-reset',
      'Totalizer accumulation mode',
      'External reset + gate input',
      'High-speed counting ≤ 5 kHz',
    ],
    specs: [
      { label: 'Panel Size', value: '96×96 MM' },
      { label: 'Display', value: '6-digit LED' },
      { label: 'Count Digits', value: '6 digits (0–999999)' },
      { label: 'Set Points', value: '2 (SP1 + SP2)' },
      { label: 'Output', value: '2 × Relay (SPDT)' },
      { label: 'Input Frequency', value: 'Up to 5 kHz' },
      { label: 'Input Type', value: 'NPN / PNP / Voltage pulse' },
      { label: 'Reset', value: 'External reset input + manual' },
      { label: 'Supply', value: '90–270 VAC' },
      { label: 'Protection', value: 'IP54 (front panel)' },
    ],
    inputs: ['NPN / PNP / Voltage pulse up to 5 kHz'],
    outputs: ['2 × SPDT Relay (SP1, SP2)'],
    applications: ['Textile yarn counting', 'Packaging machine batching', 'Bottle counting', 'Cycle counting', 'Production totalizing'],
    supply: '90–270 VAC',
    image: 'https://itherm.co.in/wp-content/uploads/2024/12/Cx-928-1-300x300.jpg',
  },
  {
    model: 'KCN-998',
    slug: 'kcn-998',
    name: 'Digital Counter KCN-998',
    category: 'timers-counters',
    categoryName: 'Timers & Counters',
    size: '96×96 MM',
    type: 'Dual Set Point Timer/Counter',
    badge: null,
    tagline: 'Combined timer and counter with dual set point',
    description:
      'The KCN-998 combines preset counting and time delay functions in the 96×96 MM panel format. Supports timer and counter modes with dual set points and relay outputs.',
    features: [
      'Timer + counter in one unit',
      'Dual set point',
      'Two relay outputs',
      'Multiple timing modes (ON delay, OFF delay, pulse)',
      'Count mode for production',
      'Wide supply range',
    ],
    specs: [
      { label: 'Panel Size', value: '96×96 MM' },
      { label: 'Display', value: '6-digit LED' },
      { label: 'Modes', value: 'Timer + Counter' },
      { label: 'Set Points', value: '2' },
      { label: 'Output', value: '2 × Relay' },
      { label: 'Supply', value: '90–270 VAC' },
    ],
    inputs: ['External trigger', 'Pulse input'],
    outputs: ['2 × SPDT Relay'],
    applications: ['Batch timing', 'Dye bath timing', 'Autoclave cycle timing', 'Machine run time'],
    supply: '90–270 VAC',
    image: 'https://itherm.co.in/wp-content/uploads/2024/12/Cx-928-1-300x300.jpg',
  },

  // ─── Humidity Controllers ───────────────────────────────────────────────────
  {
    model: 'Humi-Temp',
    slug: 'humi-temp',
    name: 'Humidity & Temperature Controller',
    category: 'humidity-controllers',
    categoryName: 'Humidity Controllers',
    size: '96×96 MM',
    type: '4 Digit Dual Row',
    badge: 'Specialty',
    tagline: 'Dual PID control for both %rH and temperature in one instrument',
    description:
      'The Humi-Temp is a dedicated dual-channel PID controller that simultaneously controls both temperature (°C) and relative humidity (%rH) in a single 96×96 MM panel instrument. Features compressor time delay protection, low water level alert, and independent PID tuning for each channel. Designed for environmental chambers, stability rooms, and cold room applications.',
    features: [
      'Simultaneous PID control for temperature + %rH',
      'Independent PID parameters for each channel',
      'Compressor time delay protection (0–9 min)',
      'Low water level alert output',
      'Dual 4-digit display (T upper, %rH lower)',
      'Auto-tune for both channels',
      'RS485 Modbus RTU (optional)',
      'Selectable ON-OFF or PID per channel',
      'Alarm outputs for high/low deviation',
    ],
    specs: [
      { label: 'Panel Size', value: '96×96 MM' },
      { label: 'Display', value: 'Dual 4-digit LED' },
      { label: 'Temperature Input', value: 'Pt-100 RTD' },
      { label: 'Humidity Input', value: 'Capacitive %rH sensor' },
      { label: 'Temperature Range', value: '-10–120 °C' },
      { label: 'Humidity Range', value: '0–99 %rH' },
      { label: 'Control Mode', value: 'PID / ON-OFF (per channel)' },
      { label: 'Output 1 (Temp)', value: 'Relay (SPDT)' },
      { label: 'Output 2 (%rH)', value: 'Relay (SPDT)' },
      { label: 'Compressor Delay', value: '0–9 min programmable' },
      { label: 'Low Water Alert', value: 'Relay output' },
      { label: 'Communication', value: 'RS485 Modbus RTU (optional)' },
      { label: 'Supply', value: '90–270 VAC, 50/60 Hz' },
      { label: 'Protection', value: 'IP54 (front panel)' },
    ],
    inputs: ['Pt-100 RTD (temperature)', 'Capacitive humidity sensor (%rH)'],
    outputs: ['Relay (heating)', 'Relay (humidification)', 'Low water alert relay'],
    communication: ['RS485 Modbus RTU (optional)'],
    applications: [
      'Stability chambers — pharma & food',
      'Environmental test chambers',
      'Cold rooms & walk-in coolers',
      'Seed storage rooms',
      'Textile conditioning rooms',
      'Museum & archive climate control',
    ],
    supply: '90–270 VAC',
    image: 'https://itherm.co.in/wp-content/uploads/2025/01/7-Humidity-Controller.jpg',
  },
  {
    model: 'RHTC-44',
    slug: 'rhtc-44',
    name: 'Humidity Controller RHTC-44',
    category: 'humidity-controllers',
    categoryName: 'Humidity Controllers',
    size: '48×48 MM',
    type: 'Single Channel',
    badge: null,
    tagline: 'Compact 48×48 relative humidity ON-OFF controller',
    description:
      'The RHTC-44 is a compact 48×48 MM single-channel relative humidity controller with ON-OFF control. Suitable for dehumidification and humidification control in small enclosures and panel environments.',
    features: [
      'Single channel %rH control',
      'ON-OFF control mode',
      'Compact 48×48 MM format',
      'Capacitive humidity sensor input',
      'Relay output',
      'Setpoint adjustment',
    ],
    specs: [
      { label: 'Panel Size', value: '48×48 MM' },
      { label: 'Display', value: '4-digit LED' },
      { label: 'Input', value: 'Capacitive %rH sensor' },
      { label: 'Range', value: '0–99 %rH' },
      { label: 'Control Mode', value: 'ON-OFF' },
      { label: 'Output', value: 'Relay (SPDT)' },
      { label: 'Supply', value: '90–270 VAC' },
    ],
    inputs: ['Capacitive humidity sensor'],
    outputs: ['1 × SPDT Relay'],
    applications: ['Panel humidity control', 'Small enclosures', 'Seed storage', 'Archives'],
    supply: '90–270 VAC',
    image: 'https://itherm.co.in/wp-content/uploads/2025/01/7-Humidity-Controller.jpg',
  },

  // ─── Data Loggers ───────────────────────────────────────────────────────────
  {
    model: 'AI-Logger',
    slug: 'ai-logger',
    name: 'Multi-Channel Data Logger',
    category: 'data-loggers',
    categoryName: 'Data Loggers',
    size: '—',
    type: 'Panel / Bench Mount',
    badge: null,
    tagline: 'Multi-channel temperature data logger for pharma validation',
    description:
      'The AI-Logger is a multi-channel data logger designed for pharmaceutical validation, cold chain monitoring, and food safety documentation. Records temperature from multiple TC/RTD sensors with time-stamped data for compliance reporting.',
    features: [
      'Multi-channel TC & RTD inputs',
      'Time-stamped data recording',
      'PC connectivity for data download',
      'Alarm logging',
      'Password-protected records',
      'Pharma-grade 21 CFR Part 11 ready documentation',
      'Graphical trend view on PC software',
    ],
    specs: [
      { label: 'Channels', value: 'Up to 8 channels (TC + RTD)' },
      { label: 'Sensor Input', value: 'J, K TC + Pt-100 RTD' },
      { label: 'Logging Interval', value: '1 sec – 60 min' },
      { label: 'Memory', value: 'Internal non-volatile memory' },
      { label: 'Interface', value: 'RS232 / USB to PC' },
      { label: 'Supply', value: '230VAC or battery' },
    ],
    inputs: ['J Thermocouple', 'K Thermocouple', 'Pt-100 RTD'],
    outputs: ['RS232 / USB data port', 'Alarm relay'],
    applications: [
      'Pharmaceutical validation',
      'Autoclave qualification',
      'Stability chamber logging',
      'Cold chain monitoring',
      'Food safety documentation',
    ],
    supply: '230VAC / Battery',
    image: 'https://itherm.co.in/wp-content/uploads/2023/04/AI-USB-Logger-e1681908640482-300x300.jpg',
  },
  {
    model: 'AI-USB-Logger',
    slug: 'ai-usb-logger',
    name: 'USB Data Logger',
    category: 'data-loggers',
    categoryName: 'Data Loggers',
    size: '—',
    type: 'Portable',
    badge: null,
    tagline: 'Portable USB-connected temperature & humidity logger',
    description:
      'The AI-USB-Logger is a compact portable logger for temperature and humidity monitoring. Data downloads directly via USB to a PC for report generation.',
    features: [
      'USB direct download',
      'Temperature & humidity recording',
      'Compact portable design',
      'Battery powered',
      'Alarm flag logging',
      'PC software for reports & graphs',
    ],
    specs: [
      { label: 'Parameters', value: 'Temperature + Humidity' },
      { label: 'Interface', value: 'USB' },
      { label: 'Memory', value: 'Up to 32,000 records' },
      { label: 'Battery', value: 'AAA × 2 (1 year life)' },
      { label: 'Display', value: 'LCD' },
    ],
    inputs: ['Integrated T + %rH sensor'],
    outputs: ['USB data download'],
    applications: ['Cold chain', 'Warehouse monitoring', 'Transit monitoring', 'Lab incubators'],
    supply: 'Battery',
    image: 'https://itherm.co.in/wp-content/uploads/2023/04/AI-USB-Logger-e1681908640482-300x300.jpg',
  },
  {
    model: 'VA-Logger',
    slug: 'va-logger',
    name: 'Autoclave Validation Logger',
    category: 'data-loggers',
    categoryName: 'Data Loggers',
    size: '—',
    type: 'Autoclave-Grade',
    badge: null,
    tagline: 'Dedicated validation logger for autoclave sterilization cycles',
    description:
      'The VA-Logger is purpose-built for autoclave sterilization cycle validation. Records temperature data from multiple probes inside the autoclave chamber and generates IQ/OQ/PQ validation reports.',
    features: [
      'Autoclave-rated high-temperature probes',
      'Multi-channel simultaneous recording',
      'F0 value calculation',
      'Validation report generation',
      'Password-protected data integrity',
      'USB download to PC',
    ],
    specs: [
      { label: 'Probes', value: 'Multiple Pt-100 RTD probes' },
      { label: 'Temp Range', value: 'Up to 150°C (autoclave rated)' },
      { label: 'F0 Calculation', value: 'Yes' },
      { label: 'Interface', value: 'USB' },
      { label: 'Report Format', value: 'PDF / Excel' },
    ],
    inputs: ['Pt-100 RTD (autoclave probes)'],
    outputs: ['USB data download', 'PDF/Excel reports'],
    applications: ['Pharmaceutical autoclave validation', 'IQ/OQ/PQ qualification', 'Hospital CSSD validation'],
    supply: 'Battery / USB powered',
    image: 'https://itherm.co.in/wp-content/uploads/2023/04/VA-Logger-e1681908650784-300x300.jpg',
  },
]

// ─── Lookup helpers ────────────────────────────────────────────────────────────

export function getProductsByCategory(categorySlug: string): Product[] {
  return ALL_PRODUCTS.filter((p) => p.category === categorySlug)
}

export function getProductBySlug(categorySlug: string, productSlug: string): Product | undefined {
  return ALL_PRODUCTS.find((p) => p.category === categorySlug && p.slug === productSlug)
}

export function getRelatedProducts(product: Product, limit = 3): Product[] {
  return ALL_PRODUCTS.filter(
    (p) => p.category === product.category && p.slug !== product.slug
  ).slice(0, limit)
}
